### ISSUE TITLE
Bugs to Fix

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#114]
### Bugs to fix

- [x] normalization, it should say "number of ranges" rather than "number of wavelengths"
- [x] **pysat/plotting/plots.py:77**: plotting ICA results gives the error: "local variable 'x_label' referenced before assignment
- [x] add a more correct `tool-tip` to `Re-run Module`
- [x] rename `Undo` button to `Re-run Module`
- [x] Darkmode is not working
- [x] **point_spectra_gui/functions/CrossValidation.py:89** Fails (This failed because of a problem within pysat. A particular function did not accept `yrange`)
- [x] **point_spectra_gui/functions/Plot.py:149**: {AttributeError}'DataFrame' object has no attribute 'df' (This error is just plot trying to check to see if there is a dataframe or not, this is not unusual)
- [x] **plot.py**: there's a blank combo box next to the field for "figure name"
- [x] baseline removal using CCAM with JSC data: "can only concatenate list (not 'str') to list"
- [x] all the defaults for the different baseline methods seem to be zero
- [x] #109 plotting I can't choose previously created figure names with the drop down. if that feature isn't working it needs to be removed
- [x] #112 split data also does not work. It doesn't list any variables on which to split
- [x] #113 Remove rows seems to work on numerical columns but not string columns. For target the only option it lists is '-'
