### ISSUE TITLE
Updating UI to Future_ implementation

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#80]
- Re applying the UI won't take too long, mostly design and convert I will be using the original UI's look.
- Applying the front end will take a while as it will require careful piecing together of Qtickle along with the dictionary
- Applying the backend will take a while as it is the messiest to deal with.
- It will require communication between the GUI and the backend with PYSAT. It will also require careful thinking about how each module will be ran and restored

- Note: The backend looks long right now, but once I finally get to it, I'll further break it down to show exactly what part of the backend is being worked on, For example the dictionary and `run()` function or the dictionary and Qtickle, the talking between PYSAT and the GUI. etc.

## idea 
- Use the data that's already in the dictionary and pass it directly to PYSAT
- we can still use the `run()` function, 
- we would simply parse through the dictionary and collect the necessary parameters for PYSAT to use
- I could potentially rename each of the object names inside the UI such that the parameters correctly match up to the sklearn functions. However, this goes against PyQt paradigm. 
- The better way would to change the dictionary index names outside of the UI.

## Pros
With this new implementation we will be able to design New UI's faster, and we will be following the basic PyQt paradigm. 
- Design with QtDesigner
- call from the UI_Form when you want to add or delete something
- Qtickle can be fully applied here to restore items correctly

## TODO

- [x] CrossValidation.py            
- [x] GP.py # Ryan said, don't worry about this one
- [x] Interpolation.py 
- [x] LoadData.py                   
- [x] MaskData.py                   
- [x] Normalization.py              
- [x] OutputFolder.py               
- [x] Plot.py                       
- [x] ReadChemCamData.py  # Finished, but not tested. In need of proper datasets
- [x] RemoveRows.py                 
- [x] StratifiedFolds.py            
- [x] MultiplyByVector.py           
- [x] DimensionalityReduction.py # PCA: 2.79s / ICA: XXXs / ICA-JADE: 410s, Long run time for ICA-Jade is normal.
- [x] PeakAreas.py # executed in: 18.39s
- [x] Plot_ICA_PCA.py # executed in: 4.23s
- [x] WriteToCSV
- [x] PLS.py                        
- [x] OLS.py                        
- [x] OMP.py                        
- [x] Lasso.py                      
- [x] ElasticNet.py                 
- [x] Ridge.py                      
- [x] BayesianRidge.py              
- [x] ARD.py                        
- [x] LARS.py                       
- [x] LassoLARS.py                  
- [x] SVR.py                        
- [x] KRR.py                        
- [x] RegressionTrain.py # Debug all training methods
- [x] RegressionPredict.py 
- [x] SubmodelPredict.py            
- [ ] BaselineRemoval.py            
- [x] PlotSpectra.py                
- [ ] SplitDataset.py # Optional [Low Priority]

**Comment by ryanbanderson** [comment]
I'm going to go ahead and keep developing UIs as we have been, just in the interest of getting new functionality working, and they can be translated to this mode later.

Keep me posted as you make progress on this!

**Comment by tisaconundrum2** [comment]
All Modules have been Implementing and reapplied.

**Comment by tisaconundrum2** [comment]
Front End work will begin tomorrow

**Comment by tisaconundrum2** [comment]
Front end pieces can now be added without having to alter the original UI file.
This means we can simply auto generate our files and leave them as they are.
![image](https://user-images.githubusercontent.com/11879769/29140408-333798c4-7cff-11e7-99bb-4d74549038f0.png)

**Comment by tisaconundrum2** [comment]
A small feature that seems to have emerged is that the widget contains itself within it's form. In other words they won't stretch uncontrollably.
![image](https://user-images.githubusercontent.com/11879769/29140458-62b5d174-7cff-11e7-94fa-d7338a151c84.png)

**Comment by tisaconundrum2** [comment]
<pre>
# 23 24 25 28 29 30 31
# [=]                     ARD.py                        1 day
# [=]                     BaselineRemoval.py            1 day    
# [=]                     BayesianRidge.py              1 day
# [=]                     CrossValidation.py            1 day    
# [=]                     DimensionalityReduction.py    1 day
# [=]                     ElasticNet.py                 1 day
# [=]                     GP.py                         1 day
# [=]                     Interpolation.py              1 day  
# [=]                     KRR.py                        1 day
# [=]                     LARS.py                       1 day
# [=]                     Lasso.py                      1 day
# [=]                     LassoLARS.py                  1 day
# [=]                     LoadData.py                   1 day
# [=]                     MaskData.py                   1 day
# [=]                     MultiplyByVector.py           1 day      
# [=]                     Normalization.py              1 day  
#    [=]                  OLS.py                        1 day
#    [=]                  OMP.py                        1 day
#    [=]                  OutputFolder.py               1 day  
#    [=]                  PeakAreas.py                  1 day
#    [=]                  Plot.py                       1 day
#    [=]                  Plot_ICA_PCA.py               1 day  
#    [=]                  PlotSpectra.py                1 day  
#    [=]                  PLS.py                        1 day
#    [=]                  ReadChemCamData.py            1 day      
#    [=]                  RegressionPredict.py          1 day      
#    [=]                  RegressionTrain.py            1 day      
#    [=]                  RemoveRows.py                 1 day
#    [=]                  Ridge.py                      1 day
#    [=]                  SplitDataset.py               1 day  
#    [=]                  StratifiedFolds.py            1 day      
#    [=]                  SubmodelPredict.py            1 day      
#    [=]                  SVR.py                        1 day
#       [=======]         Backend List                  2 - 3 days
</pre>

- [ ] ARD.py                        
- [ ] BaselineRemoval.py            
- [ ] BayesianRidge.py              
- [ ] CrossValidation.py            
- [ ] DimensionalityReduction.py    
- [ ] ElasticNet.py                 
- [ ] GP.py                         
- [ ] Interpolation.py              
- [ ] KRR.py                        
- [ ] LARS.py                       
- [ ] Lasso.py                      
- [ ] LassoLARS.py                  
- [ ] LoadData.py                   
- [ ] MaskData.py                   
- [ ] MultiplyByVector.py           
- [ ] Normalization.py              
- [ ] OLS.py                        
- [ ] OMP.py                        
- [ ] OutputFolder.py               
- [ ] PeakAreas.py                  
- [ ] Plot.py                       
- [ ] Plot_ICA_PCA.py               
- [ ] PlotSpectra.py                
- [ ] PLS.py                        
- [ ] ReadChemCamData.py            
- [ ] RegressionPredict.py          
- [ ] RegressionTrain.py            
- [ ] RemoveRows.py                 
- [ ] Ridge.py                      
- [ ] SplitDataset.py               
- [ ] StratifiedFolds.py            
- [ ] SubmodelPredict.py            
- [ ] SVR.py

**Comment by tisaconundrum2** [comment]
Merged on https://github.com/ryanbanderson/PySAT/pull/21#event-1269030475
